# Generated by Django 4.2 on 2025-05-10 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_appointment_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='my_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
