# Generated by Django 4.2 on 2025-03-17 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
