# Generated by Django 4.2 on 2025-05-28 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_service_description_en_service_description_tr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
